---
sudo: required

env:
  global:
    - MACHINE_NAME: jenkins-php
      IP: 192.168.33.21
      VM_DIR: /etc/ansible/roles/role_under_test

  matrix:
    - distribution: ubuntu
      version: 16.04
      init: /sbin/init
      run_opts: "--privileged"
      playbook: test.yml

services:
  - docker

before_install:
  # Pull container
  - 'sudo docker pull ${distribution}:${version}'
  # Customize container
  - 'sudo docker build --rm=true --file=tests/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible tests'
  # Install lint tools.
  - 'gem install rubocop'

script:
  - container_id=$(mktemp)

  # Run container in detached state
  - 'sudo docker run --detach --volume="${PWD}":${VM_DIR}:ro ${run_opts} ${distribution}-${version}:ansible "${init}" > "${container_id}"'

  # Set hostname.
  - 'sudo docker exec "$(cat ${container_id})" hostname ${HOSTNAME}'

  # Install dependencies.
  - 'sudo docker exec "$(cat ${container_id})" ansible-galaxy install -r ${VM_DIR}/ansible-requirements.yml'

  # Vagrantfile syntax check
  - 'rubocop --except LineLength,Eval,MutableConstant'

  # Ansible syntax check.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook ${VM_DIR}/provisioning/jenkins-php.yml --syntax-check'

  # Test role.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook ${VM_DIR}/provisioning/jenkins-php.yml'

  # Clean up
  - 'sudo docker stop "$(cat ${container_id})"'
