---

- hosts: all
  become: true
  vars_files:
    - "../conf/global.yml"
    - "../conf/parameters.yml"

  roles:
    - { role: common }
    - { role: geerlingguy.jenkins }
    - { role: geerlingguy.nginx }
    - { role: geerlingguy.php }
    - { role: geerlingguy.composer }
