---

- hosts: defaulthost
  become: true
  vars_files:
    - "../conf/parameters.yml"

  roles:
    - common
    - { role: ansible-role-dns, dns_forced_in_dhclientconf: false }
    - { role: geerlingguy.jenkins }
    - { role: geerlingguy.nginx }
    - { role: geerlingguy.php }
    - { role: geerlingguy.composer }
#    - { role: php-tools }
