---

- hosts: all
  become: true
  vars_files:
    - "../conf/parameters.yml"

  roles:
    - common
    - { role: geerlingguy.jenkins }
    - { role: geerlingguy.nginx }
    - { role: geerlingguy.php }
    - { role: geerlingguy.composer }
#    - { role: php-tools }
