---
- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart rsyslog
  service: name=rsyslog state=restarted
- name: restart cron
  service: name=cron state=restarted